### ISSUE TITLE
Add Fasta loading to React app

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/libqsearch-clean#11]
Add Fasta database access to the React app. Allow user to enter search terms and the number of desired samples (range 4-160)

**Comment by joyhughes** [comment]
The goal is to get enough test data to generate trees of different sizes. User should be able to input the desired number of samples without restriction.

Matrix visualization can be included in this iteration - I am writing a separate issue for this.

**Comment by joyhughes** [comment]
Fasta loading still needs to be added to [this React app](https://github.com/joyhughes/libqsearch-clean) so tree visualization can be performed

**Comment by namvdo** [comment]
Resolved by: https://github.com/namvdo/libqsearch-clean/commit/a97301a805184dae02eabaaac0768ef0fd890928
