### ISSUE TITLE
Investigate mixed extreme NCD values in matrices from FASTA

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/libqsearch-clean#16]
Matrices often have very low values (< 0.2) mixed with very high values (>0.9). Investigate why this is happening and fix if needed. Could be a bug in NCD calculation or data contamination.

**Comment by namvdo** [comment]
This is fixed by: https://github.com/namvdo/react_wasm_worker/commit/e498deed153c326533e696d58e1d24195a67ef9f
